### PR TITLE
126 tests

### PR DESCRIPTION
**Pull request by jacobnewsted**
A starting framework for testing functionality on the site. Complete with examples for both Selenium tests as well as tests on views. Readme that explains how to write tests. Any comments about wording of the readme or additional examples that would help is welcome.

### CODE REVIEW

**Comment by jacobnewsted** [comment]
Please put this on hold. I forgot to separate the test and dev requirements. I will get on that now

**Comment by jacobnewsted** [comment]
should be good to look over now

**Comment by billspat** [comment]
additional comment: thank you for creating a separate requirements file for tests  ( `tests/requirements.txt`).   However I was hoping to have that file  only have the additional packages needed for testing.     Otherwise keeping these two files in sync will be hard. 

pip allows you to put the following in the top of any file :  ` -r requirements.txt`  to "include" it

so I suggest two files:  the usual requirements.txt and a new one, not in tests, called `requirements-dev.txt`  and put that line above at a the first line, and then only the packages needed for testing and development.   that way you don't have to have things duplicated in both files.    Let me know if this works for you.

**Comment by billspat** [comment]
the documentation does say you need to run a the flask app, but it should say that at the very top.   Otherwise I get an error as soon as I run the line py.test -s

**Comment by jacobnewsted** [comment]
If the `flask run` step should be moved from the second line to the first line, maybe we should put the setup steps first and put that warning near there

**Comment by billspat** [comment]
re: requirements: if the tests requiring higher versions of anything, it's ok to update that in requirements.txt for the app.  those versions are not set in stone, they just happen to all work together.

**Comment by billspat** [comment]
the test above doesn't pass for me as the path to a file to upload is hard coded  
` uploadButton.send_keys('/Users/newsted1/Downloads/DOID-9562-STRING-Adjacency-DisGeNet-Symbols.txt')`  What I suggest is to use Flask config  which may take some work but should be worth it as we also need to set config for where to look for test job output.   

- [ ] set a new config variable TESTGENEFILE=/path/to/genefile.txt , perhaps in 
- [ ] use the config variable in test framework (or as a fixture)
- [ ] update `tests/readme.md` that a file must be available and the configuration must be set to use it

**Comment by jacobnewsted** [comment]
This is related to the integrate package, we need to fix this so that the data downloaded (or data already stored) has a path filled in (via an environment variable) abiding by the new data format.

**Comment by billspat** [comment]
time passed, code changed, tried again.   Superseded by PR #229.

**Review by billspat — COMMENTED** [review]
(submitting a review on this old PR to close out the request) revamped for latest code based, new PR #229

**Pull request closed without merging**
