### PR TITLE
136 - Results Page

### PR DESCRIPTION
**Pull request by jacobnewsted**
Added results page and models. Tweaked some things like profile updating and how jobs are stored. 
A new variable, `BASE_URL`, most be set in order for this to work. If you are working locally then the localhost or 127 URL you use is fine, if it is deployed then you need to use the URL the web app is deployed to.
If you have not recreated your DB then you need to do so in order to get the updated Results models

### CODE REVIEW

**Comment by billspat** [comment]
@jacobnewsted  I hit a problem when running a job.   To get it set-up I pulled this branch, then

1.  deleted the existing database and changed the name of the db in .env and deleted the migrations folder
2. added `'BASE_URL='127.0.0.0:5000'` to .env
3. used `flask create-db`
4. added this app to my github account and updated the .env config files
5. I can log-in with github and add an email address in my profile. 

When running a job or  opening  the `/jobs` page I get the following error that looks like it comes from my `jobs.py` module (which is going to be removed this week).    It's expecting a dictionary but gets a string for the params value.     Let me know if you have time to investigate today.  Is there a change that maybe didn't get checked in?  Again this is code that will be superseded by the new ResultsStore class so could be more efficient to just try to get it to work with that new stuff instead of debugging this.  


```
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last)

    File "/Users/billspat/miniforge3/envs/geneplexus_app/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
        def __call__(self, environ: dict, start_response: t.Callable) -> t.Any:
            """The WSGI server calls the Flask application object as the
            WSGI application. This calls :meth:`wsgi_app`, which can be
            wrapped to apply middleware.
            """

            return self.wsgi_app(environ, start_response)

    File "/Users/billspat/miniforge3/envs/geneplexus_app/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
    File "/Users/billspat/miniforge3/envs/geneplexus_app/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
    File "/Users/billspat/miniforge3/envs/geneplexus_app/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request

    rv = self.handle_user_exception(e)
    File "/Users/billspat/miniforge3/envs/geneplexus_app/lib/python3.9/site-packages/flask/app.py", line 1523, in 
full_dispatch_request

    rv = self.dispatch_request()

    File "/Users/billspat/miniforge3/envs/geneplexus_app/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

    File "/Users/billspat/Code/krishnan_lab/geneplexus_app/app/views.py", line 203, in jobs

    session_joblist = job_info_list(session_jobnames, app.config)

    File "/Users/billspat/Code/krishnan_lab/geneplexus_app/mljob/jobs.py", line 380, in job_info_list

    jobinfolist = [retrieve_job_info(jobname, app_config) for jobname in jobnames]

    File "/Users/billspat/Code/krishnan_lab/geneplexus_app/mljob/jobs.py", line 380, in <listcomp>

    jobinfolist = [retrieve_job_info(jobname, app_config) for jobname in jobnames]

    File "/Users/billspat/Code/krishnan_lab/geneplexus_app/mljob/jobs.py", line 369, in retrieve_job_info

    job_info['net_type'] = job_params.get('GP_NET_TYPE')

    AttributeError: 'str' object has no attribute 'get'

```

**Comment by billspat** [comment]
It's a browser/cookie issue.   It works on Chrome and Safari (both had no previous session at all).   even in private mode, Firefox may hold on to some kind of session value, so that the following if statements return true then when they shouldn't.  

```Python
    if 'jobs' in session:
        session_jobnames = session['jobs']
        if len(session_jobnames) > 0:
            session_joblist = job_info_list(session_jobnames, app.config)
```

My problem seems like an edge case (Firefox browser with really old cookies hanging around) so this is a new issue unrelated to this PR.

**Comment by billspat** [comment]
things to focus this PR:  
 
1. comment out anything related to Genesets in the results page since that's not functional
2. comment out the placeholders on the user drop-down that aren't functional 
3. remove 'favorite' from heading on results listing (non favorite)
4. disable the description field on the results page for public results that aren't yours

**Comment by jacobnewsted** [comment]
Issues are addressed in 0a02bb7

**Comment by billspat** [comment]
Merged locally and pushed!  but sorry I did not squash commits.    @jacobnewsted I want to confirm with you before deleting the branch.

**Pull request merged**
