### PR TITLE
merge in refactor for cloud architecture for #218

### LINKED ISSUE #218: simplified cloud architecture with azure functions
Azure Functions was previously not a viable solution due to time and memory limits, but those have been increased, and the PyGenePlexus package so far (based on profiling tests) has lower memory requirements. 

integrate azure function app for running GP jobs with the application.

### PR DESCRIPTION
**Pull request by billspat**
closes #218 
this merges user jobs and results with new results storage libs and queue runner.   It still has obsolete folders and libs that need to be deleted.  Should these be cleaned prior to merging?

### CODE REVIEW

**Comment by jacobnewsted** [comment]
The results don't get saved when you run a job logged in. Steps to reproduce:

- Login
- Select positive genes
- Run model
- Go to "My Results" in the top right menu
- There are no results tied to the account
Tested in `dev` branch and it still works

**Comment by billspat** [comment]
@jacobnewsted  I've only tested to run jobs using the azure queue functions, which _can_ be run locally but requires setup of cloud storage since I don't know a way to simulate Azure Queue storage locally (there is probably a way, but doesn't seem like any less work than just creating a queue).    I have documentation on getting it started https://github.com/krishnanlab/geneplexus_app/blob/218-cloudarch/mljob/README.md 

but I should have mentioned that when I opened this PR above!   After seeing this I think I need to get it onto Azure for you to test unless you want to follow the readme to create a new virtualenv and run the functions locally.   I can send you the storage connection string to use so you don't have to build the azure storage again.

**Comment by billspat** [comment]
I recant my previous statement : I did not incorporate JN's callbacks properly in the new queue function.   I Will add commits to this PR.

**Comment by billspat** [comment]
@jacobnewsted  : the results records are working, and tests are passing.   You may have to create or install new python envs for testing if you keep them separate.  You should be able to run locally without using queue functions and `RUN_LOCAL=True`  Thank you for reviewing again

**Pull request merged**
