### PR TITLE
Implement Password Reset

### PR DESCRIPTION
**Pull request by jacobnewsted**
This pull request does the following:
 - Adds a template for both submitting a password reset request and the reset page itself
 - Added model variables that contain token and token expiration information
 - It DOES NOT implement the emailing mechanism (line 665 in views.py)

### CODE REVIEW

**Comment by billspat** [comment]
@jacobnewsted  : what are the steps needed to implement this branch?   `flask db upgrade`?     I am getting a database error

**Comment by jacobnewsted** [comment]
while this is hardly a GOOD solution, for right now it would be best if you drop any tables you have manually and then create-db again

**Comment by billspat** [comment]
to get this working and tested on Azure: 

 - merged branch 150- into `dev` in PR #255 then merged `dev` into this branch
 - completed the password reset view code to send basic email using the notifier module.    The view functions have perhaps too much code but they work.  
 - replaced print() with logging as it's easier to view logs files using bash in app service.  currently logs the password reset email
 - tested and working on Azure using sendgrid

However I found a potential issue (see below)

**Comment by billspat** [comment]
It's possible to create a use with social login (github) and assign email address, then create a local login and assign the same email address, or create as many logins as you want and assign the same address. 

```
# flask shell
import app
from app.models import *
form_email= 'billspat@msu.edu'
users = User.query.filter_by(email=form_email)
users.all()
[<User testing MSUemail; Email billspat@msu.edu>, <User Pat Bills; Email billspat@msu.edu>, <User test dupemails; Email billspat@msu.edu>]
```

when the user resets the password, the code selects the first one of this list, but the user does not know that.    when they get an email it does not currently say the user name (which is probably should) and when they encounter the form for the password reset it doesn't show which user name, so they may not even know they've created duplicates.  

Possible solution: give the 'email' field a unique constraint so that a particular email can only be assigned to one account.

**Comment by jacobnewsted** [comment]
Added fix for email redundancy

Also added the username to the reset password page

Print statements were changed to logging statements

**Comment by billspat** [comment]
automated tests pass, manual testing shows that PW reset and email notifications work when sendgrid is configured properly, Jacob and I have been over this code so merging it in.

**Pull request merged**
